---
- name: Build and Push Docker image on Master
  hosts: master             
  gather_facts: false        
  tasks:    
    - name: Dockerfile
      copy:
        src: /var/lib/jenkins/workspace/test123/Dockerfile
        dest: /root
       
        
    - name: Index.html
      copy:
        src: /var/lib/jenkins/workspace/test123/index.html
        dest: /root
        
 
    - name: Log in to Docker Hub
      command: docker login -u bao315 -p gjqhfka123

    - name: Docker build
      command: docker build -t bao315/keduitlab:purple /root

    - name: Docker Push
      command: docker push bao315/keduitlab:purple

    - name: Deploy to Kubernetes
      command: kubectl create deploy web-purple --replicas=3 --port=80 --image=bao315/keduitlab:purple
        

    - name: Expose Service on Kubernetes
      command: kubectl expose deploy web-purple --type=LoadBalancer --port=80 --target-port=80 --name=web-purple-svc



     
