---
- name: Build and Push Docker image on Master
  hosts: master
  gather_facts: false
  become: true
  tasks:
    - name: Dockerfile
      copy:
        src: /var/lib/jenkins/workspace/test123@2/Dockerfile
        dest: /root/Dockerfile

    - name: Index.html
      copy:
        src: /var/lib/jenkins/workspace/test123@2/index.html
        dest: /root/index.html

    - name: Copy manifest file
      copy:
        src: /var/lib/jenkins/workspace/test123@2/test-deploy.yml
        dest: /root/test-deploy.yml

    - name: Log in to Docker Hub
      command: docker login -u bao315 -p gjqhfka123

    - name: Docker build
      command: docker build -t bao315/keduitlab:test12345 /root/.

    - name: Docker Push
      command: docker push bao315/keduitlab:test12345

    - name: Deploy to Kubernetes
      shell: kubectl apply -f /root/test-deploy.yml
