---
- name: Build and Push Docker image on Master
  hosts: master
  tasks:
    - name: docker -> master
      copy:
        src: "/var/lib/jenkins/workspace/test1"
        dest: "/root/"
        
    - name: Log in to Docker Hub
      shell: "docker login -u bao315 -p gjqhfka123!"

    - name: Build Docker image
      shell: "docker build -t bao315/keduitlab:puple /root/"

    - name: Push Docker image to Docker Hub
      shell: "docker push bao315/keduitlab:puple"

    - name: Deploy to Kubernetes
      shell: "kubectl create deploy web-puple --replicas=3 --port=80 --image=bao315/keduitlab:puple"


    - name: Expose Service on Kubernetes
      shell: "kubectl expose deploy web-puple --type=LoadBalancer --port=80 --target-port=80 --name=web-puple-svc"
